#ან ოპერატორი-or operator
print(True or True)#true
print(True or False)#true
print(False or True)#true
print(False or False)#false
#და ოპერატორი-and operator
print(True and True)#true
print(True and False)#false
print(False and True)#false
print(False and False)#false
