let b=document.querySelectorAll("button")
b[0].onclick=()=>alert(Math.abs(-5))
b[1].onclick=()=>{let n=+prompt();alert(Math.abs(n))}
b[2].onclick=()=>alert(Math.ceil(4.2))
b[3].onclick=()=>alert(Math.ceil(-7.8))
b[4].onclick=()=>alert(Math.floor(4.9))
b[5].onclick=()=>alert(Math.floor(-7.3))
b[6].onclick=()=>alert(Math.round(4.4))
b[7].onclick=()=>alert(Math.round(4.6))
b[8].onclick=()=>alert(Math.pow(2,5))
b[9].onclick=()=>alert(Math.pow(+prompt(),+prompt()))
b[10].onclick=()=>alert(Math.trunc(4.9))
b[11].onclick=()=>alert(Math.trunc(-7.3))
b[12].onclick=()=>alert(Math.trunc(Math.random()*10))
