print("me mqvia mate")
print("gvari chubinidze")
print("var 14 wlis")
print("12 tebervals vxvdebi 15-is")
print("var 9 klasshi")
print("davdivar kalatburtz")
print("vswavlob goashi")
print("var 56-e jgufshi")
print("minda viswavlo game developmenti")
print("me minda viyo warmatebuli programisti da kalatburteli")