age = input("Enter Your Age: ")
surname = input("Enter Your Surname: ")
name = input("Enter Your Name: ")
num1 = input("number1: ")
num2 = input("number2: ")

print(type(age))
print(type(surname))
print(type(name))
print(type(num1))
print(type(num2))